### ISSUE TITLE
Broken export of boost linking flags

### ISSUE THREAD

**Issue by tskisner** [CMB-S4/spt3g_software#70]
Hello @arahlin , just a heads up that the recent change to `Spt3gBoostPython.cmake`:

https://github.com/CMB-S4/spt3g_software/blob/a64249cfeedb855d40be02bd7afd58b55cd58a41/cmake/Spt3gBoostPython.cmake#L54

has broken the ability for the `so3g` package to get boost linking information by using the `build/cmake-install/Spt3gConfig.cmake` file.  Can you give more information about what problem that was trying to fix?  I have not yet dug into this any deeper to see why the various `Boost::filesystem`, `Boost::python`, etc are no longer available, but thought I would try to get more information about this change first.

**Comment by arahlin** [comment]
Interesting, how do you install boost, what version are you using, and what is the errors you get?  Newer boost versions ship with their own cmake config files that are supposed to provide the same variables and targets, and newer versions of cmake issue lots of warnings about potential mismatches if the cmake find module is used instead of the boost config.  This flag just suppresses that warning and tries to use the config if it can find it.
